### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by citr0net** [sicista33/waybar-scrolling-mpris#1]
Is it possible you could add the ability to change the icon using a format in the modules.json file? That would be very nice. Also love the module!

**Comment by sicista33** [comment]
Thanks your request.
I will consider the feature of icon and text customization using the config file.

**Comment by ghost** [comment]
Thank you for the response, I forked your repo to remove the icon and just added "format": "(Icon) {}". Works well accept I cant change the Icon on pause, I can't just modify the code as I use different font size for the icon.

**Comment by sicista33** [comment]
The feature has been updated. Please check it.

**Comment by sicista33** [comment]
The feature has been updated. Please check it.

**Comment by ghost** [comment]
#2 There are errors in your code and github repo
