### ISSUE TITLE
Does not Launch

### ISSUE THREAD

**Issue by citr0net** [sicista33/waybar-scrolling-mpris#2]
Error on Waybar:
[2024-10-25 19:45:25.248] [error] waybar-scrolling-mpris stopped unexpectedly, is it endless?

Error running binary using ./waybar-scrolling-mpris:
[  ~/.config/hypr/UserScripts] 󰁕 ./waybar-scrolling-mpris 
Paring json file is failed.
[2024-10-25 19:45:52.809] [error] waybar-scrolling-mpris stopped unexpectedly, is it endless?
[  ~/.config/hypr/UserScripts] 󰁕 

Also your instructions are forgetting an " at
"exec": "~/.config/hypr/UserScripts/waybar-scrolling-mpris",

**Comment by sicista33** [comment]
Is your Waybar module config file located at the correct path ('~/.config/waybar/modules')?
And I modified it to output a more detailed error message when parsing fails. If the issue is not resolved, please let me know the error message.

**Comment by ghost** [comment]
I found the error, the name of your file modules is not the same as mine (modules.json) I would recommend sourcing the main config file (~/.config/waybar/config) instead.

**Comment by CitrusIntellect** [comment]
I created a pull request to fix this issue

**Comment by sicista33** [comment]
Thank you for sharing your situation. I have updated it to use a config file specified in the Waybar documentation as the default config, including the file you recommended.

**Comment by ghost** [comment]
I just symlinked modules to modules.json, works great
